# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Port Congestion Analytics
author: Xiwen Bai
logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - blog.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/globalportcongestion/blog  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: favicon.ico
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_default_style: unsrt
    bibtex_reference_style: super
    # bibtex_bibfiles: references.bib

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - amsmath